spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookDB?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
server:
  port: 8080

